### ISSUE TITLE
Text inside JavaScript tags doesn't have syntax highlighting

### ISSUE THREAD

**Issue by yupferris** [fusetools/Fuse.AtomPlugin#10]
First of all, awesome work on this! :)

Second, highlighting JS code inside UX files doesn't seem to work as it does in the Sublime plugin:
![screen shot 2015-12-03 at 9 19 04 pm](https://cloud.githubusercontent.com/assets/3166056/11582429/834d8642-9a03-11e5-97b4-ac577285bcfb.png)

**Comment by iqingting** [comment]
not support on version 0.2.7

**Comment by Tapped** [comment]
@rguanghui That's really weird. 
You don't have language-fuse package installed? The thing is that language-fuse package is probably set as grammar language for your UX files, so the grammars shipped with fuse package is not used. Please remove language-fuse to fix that.

Thanks for reporting.

**Comment by iqingting** [comment]
ok, it's work after restart atom. thank you.

**Comment by Tapped** [comment]
Glad it worked out. I am not sure why you had to restart atom. This may as well be a bug in atom.
