### ISSUE TITLE
'fuse' could not be spawned

### ISSUE THREAD

**Issue by rodrigokiller** [fusetools/Fuse.AtomPlugin#13]
'fuse' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

It is installed and correctly in the path.

**Comment by Tapped** [comment]
Are you using Windows?

**Comment by rodrigokiller** [comment]
Yes, I am. Sorry for didnt say that.

**Comment by Tapped** [comment]
I see, hmm. So `fuse` works from cmd?

Also have you tried to restart your computer after installing fuse? Your issue have been reported by users before, however we have not found out what triggers it, but a restart should help.

**Comment by rodrigokiller** [comment]
Yes, fuse works from cmd. I will try to restart my computer later and if its works, I will report here. Thanks

**Comment by rodrigokiller** [comment]
@Tapped , it worked. Thanks, so, its all about Windows lol

**Comment by Tapped** [comment]
Good it worked, however I am not sure why Atom or Windows is not updating PATH environment properly. Most applications cache env vars though, but a restart of Atom should work in that case.

**Comment by rodrigokiller** [comment]
Don't worry, just to say, I was with SublimeText3 opened, and it was not working properly with the fuse plugin. After the restart, it worked fine.
