### ISSUE TITLE
Toggle comment not working in XML part of UX file

### ISSUE THREAD

**Issue by mastervasil** [fusetools/Fuse.AtomPlugin#16]
Toggle comment is working in JavaScript part, but not in XML part of UX files. Example:

``` XML
<Rectangle Width="1100" Height="50" Fill="#0f0" />
<JavaScript>
  console.log("Hello, FuseJS!");
</JavaScript>
```

after doing Cmd+/ on every line will become:

``` XML
<Rectangle Width="1100" Height="50" Fill="#0f0" />
<JavaScript>
  // console.log("Hello, FuseJS!");
// </JavaScript>
```

So there are 2 issues: 
- Comment doesn't work in XML part
- Comment works in `</JavaScript>` line, but in JavaScript-style

OS X 10.11.3
Atom 1.5.4
fuse 0.2.8

**Comment by Tapped** [comment]
I have resolved the first issue, however not the second one. However I am closing this one, instead keep track of your second issue here #17.
