### ISSUE TITLE
Autocomplete not working #2

### ISSUE THREAD

**Issue by mirkea-work** [fusetools/Fuse.AtomPlugin#18]
Diffferent issue related to autocomplete not working:
autocomplete doesn't seem to work when my cursor is next to ">"
https://dl.dropboxusercontent.com/u/102721494/record_160329_125603.gif

and this can be incredibly annoying

**Comment by Tapped** [comment]
Yeah, I'll have a look at this one

**Comment by Tapped** [comment]
Fixed in release 0.3.1
