### ISSUE TITLE
inspector does not work.

### ISSUE THREAD

**Issue by raphaelgodoi** [fusetools/Fuse.AtomPlugin#20]
just don't work. No elements highlighted and no inspector parameters. There's a way to debug this? I've disable all other atom communit packages.

**Comment by knatten** [comment]
Can you please try `fuse event-viewer`, and see if you get a `Fuse.Preview.SelectionChanged` event when you move your cursor to the element you want to highlight?

Does code completion work by the way?

**Comment by Sunjammer** [comment]
Note that inspector as-was has been deprecated and is not planned to make a return either.
