### ISSUE TITLE
Support for autoclosing UX tag

### ISSUE THREAD

**Issue by Sunjammer** [fusetools/Fuse.AtomPlugin#28]
UX is nice but manually writing the UX close tags all the time is a speedbump. Having automatic close of tags can be done via plugins that do it on keystroke but i'm not impressed with that approach. Having the plugin autoclose when a tag is left open, say when the > is typed but no /> would be a real speedup to workflow IMO.

**Comment by jsbeckr** [comment]
Would be nice indeed. The old autoclose plugin is a bit buggy this package is much better and works as intended: https://atom.io/packages/autoclose-tags

**Comment by jsbeckr** [comment]
Shouldn't we close this Issue then? (See the conversation in my PR)

**Comment by Tapped** [comment]
Yeah, I agree
