### ISSUE TITLE
User reported that the panel at the bottom is anoying

### ISSUE THREAD

**Issue by Tapped** [fusetools/Fuse.AtomPlugin#9]
### Different approaches - Feedback is welcome
- Only open the panel when there are errors or output data available, and make a setting for turning this feature on or off.
- Make it more clear that the panel is a fuse panel (eg. use fuse logo with text)
- Restrict the fuse panel to only be toggle based. 

Thanks for feedback by vinkla.

**Comment by onevcat** [comment]
+1 for this.
